C55XX CSL Version 2.50: RTC Inline Function
RTC Inline Function
RTC
Functions
static Uint16 rtcDivFun (Uint16 dividend, Uint16 divisor)
static Uint16 rtcModuloDivFun (Uint16 dividend, Uint16 divisor)
static Uint16 rtc_pow (Uint16 var, Uint16 pow)
function for power operator.
Function Documentation
static Uint16 rtc_pow (Uint16 var, Uint16 pow) [inline, static]
function for power operator.
===========================================================================
rtcModuloDivFun
Description
function for power operator.
Arguments
            var
            pow
Return Value Uint16
Pre Condition
NOne.
Post Condition
None
Modifies
None
===========================================================================
Parameters:
var [IN].
pow [IN].
Returns:
Uint16.
Referenced by RTC_bcdToDec(), and RTC_decToBcd().
static Uint16 rtcDivFun (Uint16 dividend, Uint16 divisor) [inline, static]
===========================================================================
rtcDivFun
Description
division of two integer number.
Arguments
            dividend         value.
            divisor          value
Return Value Uint16
Pre Condition
NOne.
Post Condition
None
Modifies
None
===========================================================================
Referenced by RTC_bcdToDec(), and RTC_decToBcd().
static Uint16 rtcModuloDivFun (Uint16 dividend, Uint16 divisor) [inline, static]
===========================================================================
rtcModuloDivFun
Description
division of two integer number.
Arguments
            dividend         value.
            divisor          value
Return Value Uint16
Pre Condition
NOne.
Post Condition
None
Modifies
None
===========================================================================
Referenced by RTC_bcdToDec(), and RTC_decToBcd().