C55XX CSL Version 2.50: CSL_RtcIsrAddr Struct Reference
CSL_RtcIsrAddr Struct Reference
RTC Data Structures
Declarations for interrupt routines.
#include <csl_rtc.h>
Data Fields
void(* MilEvtAddr)(void)
void(* SecEvtAddr)(void)
void(* MinEvtAddr)(void)
void(* HourEvtAddr)(void)
void(* DayEvtAddr)(void)
void(* ExtEvtAddr)(void)
void(* AlarmEvtAddr)(void)
Detailed Description
Declarations for interrupt routines.
Field Documentation
void(* CSL_RtcIsrAddr::AlarmEvtAddr)(void)
Alarm interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::DayEvtAddr)(void)
Day interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::ExtEvtAddr)(void)
External interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::HourEvtAddr)(void)
Hour interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::MilEvtAddr)(void)
Millisecond interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::MinEvtAddr)(void)
Minute interrupt
Referenced by RTC_setCallback().
void(* CSL_RtcIsrAddr::SecEvtAddr)(void)
Second interrupt
Referenced by RTC_setCallback().
The documentation for this struct was generated from the following file:
csl_rtc.h