C55XX CSL Version 2.50: CSL_UartIsrAddr Struct Reference
CSL_UartIsrAddr Struct Reference
UART Data Structures
UART callback pointer structure.
#include <csl_uart.h>
Data Fields
void(* lsiAddr)(void)
void(* rbiAddr)(void)
void(* tbeiAddr)(void)
void(* ctoi)(void)
Detailed Description
UART callback pointer structure.
This structure contains pointers to UART interrupt callback functions
Field Documentation
void(* CSL_UartIsrAddr::ctoi)(void)
Character timeout interrupt
Referenced by UART_setCallback().
void(* CSL_UartIsrAddr::lsiAddr)(void)
Receiver line status interrupt
Referenced by UART_setCallback().
void(* CSL_UartIsrAddr::rbiAddr)(void)
received data available and character timeout indication interrupt
Referenced by UART_setCallback().
void(* CSL_UartIsrAddr::tbeiAddr)(void)
transmiter holding register empty interrupt
Referenced by UART_setCallback().
The documentation for this struct was generated from the following file:
csl_uart.h